description=catch(Exception e) is OK
expected_problems=0